---
title: "Projet d'Analyses des données"
subtitle: "Analyse des données 'Rossignol'"
author: "Bailin CAI, Souane MOHAMED, Damian , Alexandre ZAFARI(Groupe B)"
date: "16/11/2022"
output:
  html_document:
    df_print: paged
    toc: yes
    toc_depth: 4
  pdf_document:
    toc: yes
    toc_depth: 4
  html_notebook:
    number_sections: yes
    toc: yes
    toc_depth: 4
linkcolor: red

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE, eval=TRUE}
library(tidyverse)
library(dplyr)
```

## Problématique
On va étudier la base des données sur les oiseau Rossigol


```{r Rossignol, include=FALSE, echo=TRUE}
ross <- read.table("Rossignol.csv", sep = ";", header = T)
```

## Analyse descriptive

### Pré-traitement des données

```{r, echo=FALSE}
ross %>% select(-Individus.m,-sexe.m)
ross <- data.frame(lapply(ross, function(x) {gsub(",", ".", x)}))

ross <- ross %>% mutate_at(c(-1,-3), as.numeric)
head(ross)
```


```{r, echo=FALSE}
boxplot(ross$annee.m)
hist(ross$annee.m)


```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
